# Generated by Django 2.2 on 2019-07-05 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catlog_thumb', models.CharField(blank=True, max_length=100, null=True)),
                ('catlog_name', models.CharField(blank=True, max_length=20, null=True)),
                ('catlog_keyword', models.CharField(blank=True, max_length=20, null=True)),
                ('catlog_created_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 5, 14, 29, 33, 312803), null=True)),
            ],
            options={
                'db_table': 'catlog',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 5, 14, 29, 33, 309734), null=True)),
            ],
            options={
                'db_table': 'homepage',
            },
        ),
        migrations.CreateModel(
            name='WallImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image_tags', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('image_thumb', models.CharField(blank=True, max_length=100, null=True)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 5, 14, 29, 33, 310730), null=True)),
            ],
            options={
                'db_table': 'wallimage',
            },
        ),
    ]
